// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetAppInfo():Promise<Record<string, any>>;

export function GetCurrentMod():Promise<models.ModInfo>;

export function GetModSummary():Promise<string>;

export function GetNationalFocusFiles():Promise<Array<string>>;

export function GetTechnologyFiles():Promise<Array<string>>;

export function SelectModDirectory(arg1:string):Promise<models.ValidationResult>;

export function ValidateCurrentMod():Promise<models.ValidationResult>;
