// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetCurrentMod() {
  return window['go']['app']['App']['GetCurrentMod']();
}

export function GetModSummary() {
  return window['go']['app']['App']['GetModSummary']();
}

export function GetNationalFocusFiles() {
  return window['go']['app']['App']['GetNationalFocusFiles']();
}

export function GetTechnologyFiles() {
  return window['go']['app']['App']['GetTechnologyFiles']();
}

export function SelectModDirectory(arg1) {
  return window['go']['app']['App']['SelectModDirectory'](arg1);
}

export function ValidateCurrentMod() {
  return window['go']['app']['App']['ValidateCurrentMod']();
}
